### ISSUE TITLE
BBCode syntax highlighter and text alignment

### ISSUE THREAD

**Issue by 13xforever** [chipotle/BBCode#2]
Right now selecting BBCode syntax forces soft line breaks at column 133 and aligns the text by center. This is hardly an ideal solution. Again, syntax hightlighting shouldn't do anything by provide syntax tokenization. Leave everything else to other options. At the very least, make it configurable.

**Comment by Unknow0059** [comment]
How should I go about overriding the theme? Doing so gets rid of the syntax highlighting I installed the package for, to begin with.
